#lithops: 
    #mode: serverless
    #storage: ibm_cos
    #storage_bucket: <BUCKET_NAME>
    #data_cleaner: <True/False>
    #monitoring: storage
    #workers: <MAX_NUM_OF_WORKERS>
    #data_limit: 4  # in MiB
    #execution_timeout: 1800
    #include_modules: <LIST_OF_MODULES>
    #exclude_modules: <LIST_OF_MODULES>
    #log_level: INFO
    #log_format: "%(asctime)s [%(levelname)s] %(name)s -- %(message)s"
    #log_stream: ext://sys.stdout
    #log_filename <path_to_a_file>

#localhost:
    #runtime: python3

#serverless:
    #backend: ibm_cf
    #remote_invoker: <True/False>
    #customized_runtime: <True/False>

#standalone:
    #backend: ibm_vpc
    #runtime: <RUNTIME_NAME>
    #exec_mode: consume
    #auto_dismantle: True
    #pull_runtime: <false, true>
    #hard_dismantle_timeout: 3600
    #soft_dismantle_timeout: 300

#ibm:
    #iam_api_key: <IAM KEY>

#ibm_cf:
    #endpoint : <REGION_ENDPOINT>
    #namespace : <NAMESPACE>
    #api_key : <API_KEY>
    #namespace_id : <NAMESPACE_ID> # Only for IAM auth
    #runtime : <RUNTIME_NAME>
    #runtime_timeout: 600
    #runtime_memory: 256

#code_engine:
    #namespace: <namespace id>
    #region: <namespace region>
    #docker_server: <registry server url>
    #docker_user: <registry username>
    #docker_password: <registry password>
    #kubecfg_path: <Location for kubectl yaml file>
    #runtime : <RUNTIME_NAME>
    #runtime_timeout: 600
    #runtime_memory: 256
    #runtime_cpu : 0.125

#ibm_cos:
    #region : <REGION>
    #endpoint    : <REGION_ENDPOINT>
    #private_endpoint: <PRIVATE_REGION_ENDPOINT>
    #api_key     : <API_KEY>
    #access_key : <ACCESS_KEY>  # Optional
    #secret_key : <SECRET_KEY>  # Optional

#ibm_vpc:
    #endpoint: <REGION_ENDPOINT>
    #vpc_id: <VPC_ID>
    #resource_group_id: <RESOURCE_GROUP_ID>
    #security_group_id: <SECURITY_GROUP_ID>
    #subnet_id: <SUBNET_ID>
    #key_id: <PUBLIC_KEY_ID>
    #image_id: <IMAGE_ID_FOR_VMs> # Default is ubuntu 20.04
    #ssh_user : <SSH_USER_FOR_VPC> # Default is 'root'
    #ssh_key_filename : <PATH_TO_SSH_KEYFILE> # Default path in OS
    #profile_name: <PROFILE_NAME> # Default is 'cx2-2x4'
    #master_profile_name:  <PROFILE_NAME> # Default is 'cx2-2x4'
    #delete_on_dismantle: <True/False> # Default is 'True

#vm:
    #ip_address: <IP_ADDRESS>
    #ssh_user: <SSH_USERNAME>
    #ssh_password: <SSH_PASSWORD>

#rabbitmq:
    #amqp_url   : <RABBIT_AMQP_URL>  # amqp://

#knative:
   #istio_endpoint  : <ISTIO_INGRESS_ENDPOINT>
   #docker_user     : <DOCKER_HUB_USERNAME>
   #docker_token    : <DOCKER_HUB_TOKEN>
   #runtime: <RUNTIME_NAME>
   #runtime_timeout: 600
   #runtime_memory: 256
   #runtime_cpu : 0.125

#openwhisk:
    #endpoint    : <OW_ENDPOINT>
    #namespace   : <NAMESPACE>
    #api_key     : <AUTH_KEY>
    #insecure    : <True/False>
    #runtime : <RUNTIME_NAME>
    #runtime_timeout: 600
    #runtime_memory: 256

#swift:
    #auth_url   : <SWIFT_AUTH_URL>
    #region     : <SWIFT_REGION>
    #user_id    : <SWIFT_USER_ID>
    #project_id : <SWIFT_PROJECT_ID>
    #password   : <SWIFT_PASSWORD>

#infinispan:
    #username   : <USER_NAME>
    #password   : <PASSWORD>
    #endpoint   : <INFINISPAN_SERVER_URL:PORT>
    #cache_manager : <CACHE MANAGER> # Optional
  
#ceph:
    #endpoint: <ENDPOINT_URL>
    #access_key: <ACCESS_KEY>
    #secret_key: <ACCESS_KEY>
    
#redis:
    #host: <ENDPOINT_URL>
    #port: <ACCESS_KEY>
    #password: <ACCESS_KEY>
