name: "on-pull-request"

on:
  pull_request:
    branches:
      - master
  
  workflow_dispatch: 
  # this allows to run the workflow manually through the github dashboard


jobs:

  determine_runnable_jobs:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest

    env:
       HAVE_LITHOPS_CONFIG: ${{ secrets.LITHOPS_CONFIG != '' }}

    outputs:
      localhost: ${{ steps.script.outputs.localhost }}
      ibm_cf: ${{ steps.script.outputs.ibm_cf }}
      code_engine: ${{ steps.script.outputs.code_engine }}

    steps:
      - name: Clone Lithops repository
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set jobs to run
        id: script
        run: |
          echo "localhost=true" >> $GITHUB_OUTPUT
          echo "ibm_cf=false" >> $GITHUB_OUTPUT
          echo "code_engine=false" >> $GITHUB_OUTPUT


  localhost_tests:
    runs-on: ubuntu-latest
    needs: determine_runnable_jobs
    if: needs.determine_runnable_jobs.outputs.localhost == 'true'

    steps:
      - name: Print github.action_path
        run: echo $GITHUB_WORKSPACE

      - name: Clone Lithops repository
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Lithops
        run: |
          python3 setup.py install

      - name: Run Lithops tests
        run: |
          lithops verify -b localhost -s localhost


  ce_cos_tests:
    runs-on: ubuntu-latest
    needs: determine_runnable_jobs
    if: needs.determine_runnable_jobs.outputs.code_engine == 'true'

    steps:
      - name: Print github.action_path
        run: echo $GITHUB_WORKSPACE

      - name: Clone Lithops repository
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Lithops
        run: |
          python3 setup.py install

      - name: Install Lithops config
        id: config
        run: |
          echo -n -e "${{ secrets.LITHOPS_CONFIG }}" > /tmp/lithops_config.yaml

      - name: Build new runtime
        env:
            LITHOPS_CONFIG_FILE: /tmp/lithops_config.yaml
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
          cd runtime/code_engine
          lithops runtime build -f Dockerfile.githubci ${{ secrets.DOCKER_USER }}/lithops-ce-gihub-ci:${{ github.run_id }} -b code_engine
          sed -i '/runtime: lithops-ce/c\    runtime: '${{ secrets.DOCKER_USER }}'/lithops-ce-gihub-ci:'${{ github.run_id }} /tmp/lithops_config.yaml

      - name: Run Lithops tests
        env:
          LITHOPS_CONFIG_FILE: /tmp/lithops_config.yaml
        run: |
          lithops verify -b code_engine -s ibm_cos -k

      - name: Delete Lithops CE runtime
        if: needs.determine_runnable_jobs.outputs.code_engine == 'true'
        env:
          LITHOPS_CONFIG_FILE: /tmp/lithops_config.yaml
        run: |
          lithops runtime delete ${{ secrets.DOCKER_USER }}/lithops-ce-gihub-ci:${{ github.run_id }} -b code_engine -s ibm_cos


  cf_cos_tests:
    runs-on: ubuntu-latest
    needs: determine_runnable_jobs
    if: needs.determine_runnable_jobs.outputs.ibm_cf == 'true'

    steps:
      - name: Print github.action_path
        run: echo $GITHUB_WORKSPACE

      - name: Clone Lithops repository
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Lithops
        run: |
          python3 setup.py install

      - name: Install Lithops config
        id: config
        run: |
          echo -n -e "${{ secrets.LITHOPS_CONFIG }}" > /tmp/lithops_config.yaml

      - name: Build new runtime
        env:
          LITHOPS_CONFIG_FILE: /tmp/lithops_config.yaml
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
          cd runtime/ibm_cf
          lithops runtime build -f Dockerfile.githubci ${{ secrets.DOCKER_USER }}/lithops-cf-gihub-ci:${{ github.run_id }} -b ibm_cf
          sed -i '/runtime: lithops-cf/c\    runtime: '${{ secrets.DOCKER_USER }}'/lithops-cf-gihub-ci:'${{ github.run_id }} /tmp/lithops_config.yaml

      - name: Run Lithops tests
        env:
          LITHOPS_CONFIG_FILE: /tmp/lithops_config.yaml
        run: |
          lithops verify -b ibm_cf -s ibm_cos -k

      - name: Delete Lithops CF runtime
        env:
          LITHOPS_CONFIG_FILE: /tmp/lithops_config.yaml
        run: |
          lithops runtime delete ${{ secrets.DOCKER_USER }}/lithops-cf-gihub-ci:${{ github.run_id }} -b ibm_cf -s ibm_cos
