name: "PR git-action"

on:
  pull_request:
    branches:
      - master


jobs:

  Determine_Runnable_Jobs:
    runs-on: ubuntu-latest
    outputs:
      jobs_to_run: ${{ steps.script.outputs.string }}
    steps:
      - name: Clone Lithops repository
        uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Determine which jobs to run
        id: script
        run: |
          value=$(python3 ./lithops/scripts/check_job_on_list.py "${GITHUB_WORKFLOW}")
          echo "::set-output name=string::$value"


  CE_COS:
    runs-on: ubuntu-latest
    needs: Determine_Runnable_Jobs
    if: contains(needs.Determine_Runnable_Jobs.outputs.jobs_to_run,'CE_COS')

    steps:
      - name: print-github.action_path
        run: echo $GITHUB_WORKSPACE
      - name: Clone Lithops repository
        uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        run: |
          python3 setup.py develop
      - name: install secrets in lithops config
        run: python3 ./lithops/scripts/config_fill_secrets.py "CE_COS" "${GITHUB_ACTOR,,}" "${{secrets.IAMAPIKEY }}" "${{secrets.CE_COS_API }}"
      - name: Clean CE's dedicated bucket
        run: lithops clean -c lithops/tests/config_files/lithops_config_CE_COS.yaml
      - name: build new runtime
        env:
            LITHOPS_CONFIG_FILE: ${{ github.workspace }}/lithops/tests/config_files/lithops_config_CE_COS.yaml
        run: |
         docker login -u cohenjomer -p "${{ secrets.DOCKER_TOKEN }}"
         cd runtime/code_engine
         lithops runtime build cohenjomer/lithops-ce-"${GITHUB_ACTOR,,}" -b code_engine

      - name: Run Python tests
        run: |
         lithops verify -k -c lithops/tests/config_files/lithops_config_CE_COS.yaml


  CF_COS:
    runs-on: ubuntu-latest
    needs: Determine_Runnable_Jobs
    if: contains(needs.Determine_Runnable_Jobs.outputs.jobs_to_run,'CF_COS')

    steps:
      - name: Clone Lithops repository
        uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        run: |
          python3 setup.py develop
      - name: install secrets in lithops config
        run: python3 ./lithops/scripts/config_fill_secrets.py "CF_COS" "${GITHUB_ACTOR,,}" "${{ secrets.IAMAPIKEY }}" "${{ secrets.CF_COS_API }}" "${{ secrets.CF_API_KEY }}"
      - name: Clean CF's dedicated bucket
        run: lithops clean -c lithops/tests/config_files/lithops_config_CF_COS.yaml
      - name: build new runtime
        env:
          LITHOPS_CONFIG_FILE: ${{ github.workspace }}/lithops/tests/config_files/lithops_config_CF_COS.yaml
        run: |
          docker login -u cohenjomer -p "${{ secrets.DOCKER_TOKEN }}"
          cd runtime/ibm_cf
          lithops runtime build -f Dockerfile.python38 cohenjomer/lithops-cf-"${GITHUB_ACTOR,,}"

      - name: Run Python tests
        run: |
          lithops verify -k -c lithops/tests/config_files/lithops_config_CF_COS.yaml


  LOCAL_HOST:
    runs-on: ubuntu-latest
    needs: Determine_Runnable_Jobs
    if: contains(needs.Determine_Runnable_Jobs.outputs.jobs_to_run,'LOCAL_HOST')

    steps:
      - name: Clone Lithops repository
        uses: actions/checkout@v2
      - name: Install Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        run: |
          python3 setup.py develop

      - name: Run Python tests
        env:
          LITHOPS_CONFIG_FILE: ${{ github.workspace }}/lithops/tests/config_files/lithops_config_LOCAL.yaml
        run: |
          lithops verify





